plugins {
    id 'com.android.application'
}

android {
    namespace 'com.carlyrix.app'
    compileSdk 33

    defaultConfig {
        applicationId "com.carlyrix.app"
        minSdk 21
        targetSdk 33
        versionCode 4
        versionName "4.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
